version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
    commands:
      - echo 'install phase'

  pre_build:
    on-failure: ABORT
    commands:
      - echo 'logging in to ECR'
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 339712724064.dkr.ecr.us-east-1.amazonaws.com
    
  build:
    on-failure: ABORT
    commands:
      - echo 'build phase'
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG

    
  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG
