version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
    commands:
      - echo 'install phase'

  pre_build:
    on-failure: ABORT
    commands:
      - echo 'pre_build phase'
    
  build:
    on-failure: ABORT
    commands:
      - echo 'build phase'
    
  post_build:
    on-failure: ABORT
    commands:
      - echo 'post build phase'
